<?php

declare(strict_types=1);

require __DIR__ . '/includes/data.php';
require_once __DIR__ . '/includes/integrations.php';
$pageTitle = 'Secure checkout — Gawdee';
$pageDescription = 'Complete your Gawdee order with secure online payment or cash on delivery.';
$bodyClass = 'checkout-page';
$checkoutCustomer = gawdee_customer();
require __DIR__ . '/includes/header.php';
?>
<section class="checkout-shell" data-checkout data-csrf="<?= htmlspecialchars(gawdee_csrf_token()) ?>" data-cod-enabled="<?= gawdee_setting('cod_enabled', '1') ?>" data-razorpay-enabled="<?= gawdee_razorpay_configured() ? '1' : '0' ?>" data-offer-code="<?= htmlspecialchars(gawdee_setting('offer_code', 'FREEDOM10')) ?>" data-offer-percent="<?= (int) gawdee_setting('offer_percent', '10') ?>" data-free-shipping="<?= (int) gawdee_setting('free_shipping_threshold', '999') ?>" data-shipping-fee="<?= (int) gawdee_setting('shipping_fee', '99') ?>">
    <div class="checkout-heading"><a href="index.php"><i class="ph ph-arrow-left"></i> Continue shopping</a><span class="eyebrow">Secure checkout</span><h1>Almost there.<br><em>Let’s deliver goodness.</em></h1><p>Your totals are recalculated securely on the server before payment.</p></div>
    <?php if ($checkoutCustomer): ?><div class="checkout-account-banner"><span><i class="ph ph-user-circle-check"></i></span><div><strong>Checking out as <?= htmlspecialchars($checkoutCustomer['name']) ?></strong><p>This order will appear automatically in your account and tracking dashboard.</p></div><a href="account.php">My account <i class="ph ph-arrow-right"></i></a></div><?php else: ?><div class="checkout-account-banner checkout-account-banner--guest"><span><i class="ph ph-user"></i></span><div><strong>Want order history and tracking?</strong><p>Sign in before placing the order and we’ll connect every delivery update to your dashboard.</p></div><a href="login.php?return=checkout.php">Sign in <i class="ph ph-arrow-right"></i></a></div><?php endif; ?>
    <div class="checkout-grid">
        <form class="checkout-form" data-checkout-form>
            <section class="checkout-card"><div class="checkout-card__heading"><span>01</span><div><h2>Contact</h2><p>For order and delivery updates</p></div></div><div class="checkout-fields"><label class="checkout-span-2"><span>Full name</span><input name="name" autocomplete="name" required value="<?= htmlspecialchars((string) ($checkoutCustomer['name'] ?? '')) ?>"></label><label><span>Email</span><input type="email" name="email" autocomplete="email" required value="<?= htmlspecialchars((string) ($checkoutCustomer['email'] ?? '')) ?>" <?= $checkoutCustomer ? 'readonly' : '' ?>></label><label><span>Phone</span><input type="tel" name="phone" autocomplete="tel" required value="<?= htmlspecialchars((string) ($checkoutCustomer['phone'] ?? '')) ?>"></label></div></section>
            <section class="checkout-card"><div class="checkout-card__heading"><span>02</span><div><h2>Delivery address</h2><p>Currently shipping across India</p></div></div><div class="checkout-fields"><label class="checkout-span-2"><span>Address line 1</span><input name="address1" autocomplete="address-line1" required value="<?= htmlspecialchars((string) ($checkoutCustomer['address1'] ?? '')) ?>"></label><label class="checkout-span-2"><span>Address line 2 <small>Optional</small></span><input name="address2" autocomplete="address-line2" value="<?= htmlspecialchars((string) ($checkoutCustomer['address2'] ?? '')) ?>"></label><label><span>City</span><input name="city" autocomplete="address-level2" required value="<?= htmlspecialchars((string) ($checkoutCustomer['city'] ?? '')) ?>"></label><label><span>State</span><input name="state" autocomplete="address-level1" required value="<?= htmlspecialchars((string) ($checkoutCustomer['state'] ?? '')) ?>"></label><label><span>Pincode</span><input name="pincode" inputmode="numeric" pattern="[1-9][0-9]{5}" maxlength="6" autocomplete="postal-code" required value="<?= htmlspecialchars((string) ($checkoutCustomer['pincode'] ?? '')) ?>"></label><label><span>Order note <small>Optional</small></span><input name="notes" maxlength="500"></label></div></section>
            <section class="checkout-card"><div class="checkout-card__heading"><span>03</span><div><h2>Offer & payment</h2><p>Apply a code and choose your payment method</p></div></div><div class="checkout-coupon"><label><span>Offer code</span><div><input name="coupon_code" maxlength="30" placeholder="<?= htmlspecialchars(gawdee_setting('offer_code', 'FREEDOM10')) ?>"><button type="button" data-apply-coupon>Apply</button></div><small data-coupon-message>Use <?= htmlspecialchars(gawdee_setting('offer_code', 'FREEDOM10')) ?> for <?= (int) gawdee_setting('offer_percent', '10') ?>% off.</small></label></div><div class="payment-options"><?php if (gawdee_razorpay_configured()): ?><label><input type="radio" name="payment_method" value="razorpay" checked><span><i class="ph ph-credit-card"></i><strong>Razorpay</strong><small>Cards, UPI, wallets and netbanking</small></span></label><?php endif; ?><?php if (gawdee_setting('cod_enabled','1')==='1'): ?><label><input type="radio" name="payment_method" value="cod" <?= gawdee_razorpay_configured() ? '' : 'checked' ?>><span><i class="ph ph-hand-coins"></i><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label><?php endif; ?><?php if (!gawdee_razorpay_configured() && gawdee_setting('cod_enabled','1')!=='1'): ?><div class="checkout-payment-offline"><i class="ph ph-warning-circle"></i><span><strong>Checkout is temporarily paused.</strong>Please contact the store to place your order.</span></div><?php endif; ?></div></section>
            <div class="checkout-error" data-checkout-error hidden></div>
            <button class="checkout-submit" type="submit" data-checkout-submit><span>Place secure order</span><i class="ph ph-lock-key"></i></button>
            <p class="checkout-secure-note"><i class="ph ph-shield-check"></i> Payment confirmation is verified on Gawdee’s server before an order is marked paid.</p>
        </form>
        <aside class="checkout-summary"><div class="checkout-summary__top"><span>Your order</span><strong data-checkout-count>0 items</strong></div><div class="checkout-summary__items" data-checkout-items></div><div class="checkout-summary__empty" data-checkout-empty><i class="ph ph-shopping-bag-open"></i><h2>Your bag is empty</h2><a href="index.php#shop">Browse products</a></div><div class="checkout-totals" data-checkout-totals hidden><p><span>Subtotal</span><strong data-checkout-subtotal>₹0</strong></p><p data-checkout-discount-row hidden><span>Offer discount</span><strong data-checkout-discount>−₹0</strong></p><p><span>Delivery</span><strong data-checkout-shipping>₹0</strong></p><p class="checkout-totals__grand"><span>Total</span><strong data-checkout-total>₹0</strong></p><small data-checkout-delivery-note></small></div><div class="checkout-assurance"><div><i class="ph ph-lock-key"></i><span><strong>Secure payment</strong>Server-verified checkout</span></div><div><i class="ph ph-truck"></i><span><strong>Order tracking</strong>Manual or DTDC fulfilment</span></div></div></aside>
    </div>
</section>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="assets/js/checkout.js" defer></script>
<?php require __DIR__ . '/includes/footer.php'; ?>
