-- Gawdee Storefront MySQL Dump
-- Generated at 2026-09-02 17:23:04
SET foreign_key_checks = 0;
SET NAMES utf8mb4;

-- Table structure and data for table `users` --
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `address1`, `address2`, `city`, `state`, `pincode`, `created_at`, `last_login_at`, `updated_at`) VALUES ('1', 'Bruno Harding', 'rulu@mailinator.com', '$2y$10$0eh7oy3yfL5E/1DAgQ.2AOc87bLqN14KTiJc6.r13oSB7PcPm/OgK', 'customer', '+1 (957) 573-4056', '96 Rocky Milton Freeway', 'Eos quae explicabo', 'Enim unde est numqua', 'Consectetur maxime', '643235', '2026-09-02 15:07:14', NULL, '2026-09-02 15:16:03');
INSERT INTO `users` (`id`, `name`, `email`, `password_hash`, `role`, `phone`, `address1`, `address2`, `city`, `state`, `pincode`, `created_at`, `last_login_at`, `updated_at`) VALUES ('2', 'Sopoline Luna', 'kawyv@mailinator.com', '$2y$10$f0W18PEOgb2fcLs4AGmMd.UZdmw4BSJSwetguyXNky4x5C953BQnK', 'admin', '', '', '', '', '', '', '2026-09-02 15:13:45', NULL, '2026-09-02 15:13:45');

-- Table structure and data for table `settings` --
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('store_name', 'Gawdee', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('store_email', 'info@gawdee.com', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('store_phone', '+91 70552 07030', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('currency', 'INR', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('free_shipping_threshold', '999', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('shipping_fee', '99', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('cod_enabled', '1', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_enabled', '0', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('offer_code', 'FREEDOM10', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('offer_percent', '10', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('offer_popup_enabled', '1', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('offer_popup_image', 'assets/images/independence-offer-popup-v1.webp', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('offer_popup_delay_ms', '850', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_provider', 'groq', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('groq_model', 'llama-3.3-70b-versatile', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('openai_model', 'gpt-5.6-luna', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_chat_enabled', '1', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_auto_blog_enabled', '0', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_blog_frequency_days', '7', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_blog_topics', 'traditional Indian foods, ingredient transparency, family wellness, mindful nutrition', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('ai_last_blog_at', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('razorpay_key_id', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_booking_endpoint', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_tracking_endpoint', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_customer_code', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_service_type', 'EXPRESS', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('dtdc_pickup_pincode', '', '0', '2026-09-02 13:10:51');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('site_body_font', 'system', '0', '2026-09-02 14:12:29');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('site_heading_font', 'system', '0', '2026-09-02 14:12:29');
INSERT INTO `settings` (`setting_key`, `setting_value`, `is_secret`, `updated_at`) VALUES ('site_base_font_size', '16', '0', '2026-09-02 14:12:29');

-- Table structure and data for table `products` --
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('mixme-choco', 'gawdee-mixme-choco-500-g', 'MixMe Choco', 'Gawdee MixMe — Choco 500g', 'Nutrition', 'nutrition', 'Family favourite', '759', '799', '500 g', 'assets/images/products/mixme-choco.webp', 'A smooth daily nutrition blend made with ragi, dates, jaggery, nuts, grains and seeds.', '#d96b43', '90', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('mixme-elaichi', 'gawdee-mixme-elaichi-500-g', 'MixMe Elaichi', 'Gawdee MixMe — Elaichi 500g', 'Nutrition', 'nutrition', 'No refined sugar', '759', '799', '500 g', 'assets/images/products/mixme-elaichi.webp', 'A fragrant elaichi nutrition mix created for children, adults and seniors.', '#7fa143', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('ghee-500', 'gawdee-gir-cow-a2-ghee-500-ml', 'A2 Gir Cow Ghee', 'Gawdee Gir Cow A2 Ghee 500ml', 'Ghee', 'ghee', 'Bilona method', '891', '1049', '500 ml', 'assets/images/products/ghee-500.webp', 'Traditionally prepared Gir cow ghee with a rich aroma and slow-crafted character.', '#d8a934', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('forest-honey', 'gawdee-raw-wild-forest-honey-650-g', 'Raw Forest Honey', 'Gawdee Raw Wild Forest Honey 650g', 'Honey', 'honey', 'Raw & unrefined', '650', '699', '650 g', 'assets/images/products/forest-honey.webp', 'Wild forest honey with its naturally deep flavour, aroma and thickness intact.', '#ad6f2d', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('taral-drop', 'gawdee-taral-drop-30-ml', 'Taral Drop', 'Gawdee Taral Drop 30ml', 'Wellness', 'wellness', 'Ayurvedic ritual', '209', '299', '30 ml', 'assets/images/products/taral-drop.webp', 'A compact daily wellness ritual inspired by traditional Ayurvedic practice.', '#8a663e', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('moringa', 'gawdee-moringa-powder-300-g', 'Moringa Powder', 'Gawdee Moringa Powder 300g', 'Wellness', 'wellness', 'Leaf to life', '261', '349', '300 g', 'assets/images/products/moringa.webp', 'Finely milled moringa leaf powder for simple, plant-led everyday nourishment.', '#5e7e3e', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('burra-sugar', 'gawdee-bura-sugar-1-kg', 'Burra Sugar', 'Gawdee Burra Sugar 1kg', 'Natural sugar', 'sugar', 'Khandsari', '159', '199', '1 kg', 'assets/images/products/burra-sugar.webp', 'Traditional khandsari sugar for tea, milk, sweets, desserts and everyday cooking.', '#8b5b35', '99', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `products` (`id`, `slug`, `name`, `full_name`, `category`, `category_key`, `tag`, `price`, `original_price`, `weight`, `image`, `description`, `accent`, `stock`, `stock_status`, `sku`, `source_id`, `source_url`, `rating`, `review_count`, `gallery_json`, `details_json`, `is_active`, `created_at`, `updated_at`) VALUES ('white-sugar', 'gawdee-white-sugar-1kg', 'Sulphur-Free Sugar', 'Gawdee Sulphur-Free White Sugar 1kg', 'Natural sugar', 'sugar', 'Everyday staple', '159', '199', '1 kg', 'assets/images/products/white-sugar.webp', 'A clean everyday sweetener made without sulphur treatment.', '#b8975b', '100', 'in_stock', '', '', '', '0', '0', '[]', '{}', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');

-- Table structure and data for table `banners` --
INSERT INTO `banners` (`id`, `title`, `desktop_image`, `mobile_image`, `link_url`, `alt_text`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'Independence Day wellness offer', 'assets/images/hero-slide-independence-v5.webp', 'assets/images/hero-slide-independence-mobile-v5.webp', '#shop', 'Happy Independence Day. Flat 10% off with code FREEDOM10. Featuring exact Gawdee A2 Gir Cow Ghee, Burra Sugar and MixMe Choco packs.', '10', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `banners` (`id`, `title`, `desktop_image`, `mobile_image`, `link_url`, `alt_text`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'Traditional A2 Ghee', 'assets/images/hero-slide-ghee-v5.webp', 'assets/images/hero-slide-ghee-mobile-v5.webp', 'product.php?slug=gawdee-gir-cow-a2-ghee-500-ml', 'Freedom to choose pure tradition with Gawdee Bilona-crafted A2 Gir Cow Ghee.', '20', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `banners` (`id`, `title`, `desktop_image`, `mobile_image`, `link_url`, `alt_text`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'MixMe daily nutrition', 'assets/images/hero-slide-mixme-v5.webp', 'assets/images/hero-slide-mixme-mobile-v5.webp', 'product.php?slug=gawdee-mixme-choco-500-g', 'Celebrate everyday wellness with Gawdee MixMe Choco.', '30', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');

-- Table structure and data for table `cms_sections` --
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('hero', '100% pure • natural • tested', 'Pure by Nature. Trusted for Generations.', 'Made from the milk of free-grazed Gir cows. Our A2 Ghee is bilona-churned in small batches to bring you pure nutrition that your family deserves.', '', 'assets/images/gawdee-a2-farm-hero-v1.png', '', '', 'Shop A2 Ghee', 'products.php?category=ghee', '1', '10', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('shop', 'Everyday favourites', 'Bestsellers', 'Handpicked products for everyday family routines.', '', '', '', '', 'View all products', 'products.php', '1', '20', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('categories', 'Browse the pantry', 'Shop by category', 'Find the right products for your daily rituals.', '', '', '', '', '', '', '1', '30', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('offer', 'Independence Day offer', 'Flat 10% OFF', 'On all products. Use code FREEDOM10 at checkout.', 'Celebrate with better everyday wellness.', 'assets/images/independence-day-offer-banner-v1.png', 'assets/images/independence-day-offer-banner-mobile-v1.png', '', 'Shop offer', '#shop', '1', '40', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('combos', 'Thoughtful bundles', 'Healthy combos. Greater savings.', 'Pairs designed to make everyday wellness simpler.', '', '', '', '', '', '', '1', '50', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('about', 'Rooted in purity', 'Inspired by nature', 'A wholesome journey from earth to plate.', 'We bring pure A2 Gir Cow Ghee, natural honey, grain foods and wellness products made with care, authenticity and village-inspired goodness.', '', '', '', '', '', '1', '60', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('why', 'The Gawdee difference', 'Why choose Gawdee', 'Purity, tradition and nutrition for a healthier lifestyle.', '', '', '', '', '', '', '1', '70', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('reviews', 'Customer stories', 'Loved by families who choose purity daily', 'Real words from customers who value authentic taste and thoughtful quality.', '', '', '', '', '', '', '1', '80', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('stories', 'Gawdee journal', 'Stories for a more thoughtful table', 'Ideas, traditions and ingredient knowledge for everyday wellness.', '', 'assets/images/blogs/blog-tree-laptop-reference-v1.png', '', '', 'View more', 'blog.php', '1', '90', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('reels', 'Made with care', 'From nature to your plate', 'A closer look at the products and people behind Gawdee.', '', '', '', '', '', '', '1', '100', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('newsletter', 'Stay close to goodness', 'Be the first to know!', 'Subscribe for special offers, health tips and updates.', '', '', '', '', 'Subscribe', '#', '1', '110', '2026-09-02 13:10:51');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('benefits', 'Everyday assurance', 'Pure nutrition, made simply', 'Five reasons families choose Gawdee for their daily pantry.', '', '', '', '', '', '', '1', '15', '2026-09-02 14:12:29');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('process', 'From farm to family', 'From Our Farms to Your Family', 'A slow, transparent process from free-grazed Gir cows to every jar.', '', '', '', '', '', '', '1', '35', '2026-09-02 14:12:29');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('assurance', 'Our promise', 'Goodness without shortcuts', 'Natural ingredients, careful testing and traditional preparation.', '', '', '', '', '', '', '1', '55', '2026-09-02 14:12:29');
INSERT INTO `cms_sections` (`section_key`, `eyebrow`, `title`, `subtitle`, `body`, `image`, `mobile_image`, `video_url`, `button_label`, `button_url`, `is_active`, `sort_order`, `updated_at`) VALUES ('video_testimonials', 'Watch their stories', 'Real families. Real Gawdee experiences.', 'Hear directly from customers who have made Gawdee part of their everyday routine.', '', '', '', '', '', '', '1', '85', '2026-09-02 14:12:29');

-- Table structure and data for table `testimonials` --
INSERT INTO `testimonials` (`id`, `name`, `initials`, `avatar`, `product_name`, `product_slug`, `quote`, `rating`, `theme`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'Neha Shah', 'NS', 'assets/images/testimonials/neha-shah.png', 'Raw Forest Honey', 'gawdee-raw-wild-forest-honey-650-g', 'What I love most is that the honey tastes naturally rich without feeling overly processed or artificially sweet.', '5', 'honey', '10', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `testimonials` (`id`, `name`, `initials`, `avatar`, `product_name`, `product_slug`, `quote`, `rating`, `theme`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'Pooja Desai', 'PD', 'assets/images/testimonials/pooja-desai.png', 'A2 Gir Cow Ghee', 'gawdee-gir-cow-a2-ghee-500-ml', 'The aroma feels beautifully traditional, and it has become a trusted part of our family meals.', '5', 'ghee', '20', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `testimonials` (`id`, `name`, `initials`, `avatar`, `product_name`, `product_slug`, `quote`, `rating`, `theme`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'Ritu Sharma', 'RS', '', 'MixMe Choco', 'gawdee-mixme-choco-500-g', 'A simple way to add better everyday nutrition. My children genuinely enjoy the flavour.', '5', 'mixme', '30', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `testimonials` (`id`, `name`, `initials`, `avatar`, `product_name`, `product_slug`, `quote`, `rating`, `theme`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('4', 'Ananya Rao', 'AR', '', 'Moringa Powder', 'gawdee-moringa-powder-300-g', 'Clean, convenient and easy to add to my routine. The ingredient story gives me confidence.', '5', 'moringa', '40', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');

-- Table structure and data for table `homepage_media` --
INSERT INTO `homepage_media` (`id`, `section_key`, `media_type`, `title`, `subtitle`, `file_path`, `poster_path`, `external_url`, `link_url`, `alt_text`, `product_slug`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'reels', 'image', 'Pure A2 Ghee', 'Bilona-crafted everyday goodness', 'assets/images/products/ghee-500.webp', '', '', 'product.php?slug=gawdee-gir-cow-a2-ghee-500-ml', 'Gawdee A2 Gir Cow Ghee', 'gawdee-gir-cow-a2-ghee-500-ml', '10', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `homepage_media` (`id`, `section_key`, `media_type`, `title`, `subtitle`, `file_path`, `poster_path`, `external_url`, `link_url`, `alt_text`, `product_slug`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'reels', 'image', 'Raw Forest Honey', 'Naturally rich and thoughtfully sourced', 'assets/images/products/forest-honey.webp', '', '', 'product.php?slug=gawdee-raw-wild-forest-honey-650-g', 'Gawdee Raw Forest Honey', 'gawdee-raw-wild-forest-honey-650-g', '20', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');
INSERT INTO `homepage_media` (`id`, `section_key`, `media_type`, `title`, `subtitle`, `file_path`, `poster_path`, `external_url`, `link_url`, `alt_text`, `product_slug`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'reels', 'image', 'MixMe Choco', 'Family nutrition made delicious', 'assets/images/products/mixme-choco.webp', '', '', 'product.php?slug=gawdee-mixme-choco-500-g', 'Gawdee MixMe Choco', 'gawdee-mixme-choco-500-g', '30', '1', '2026-09-02 13:10:51', '2026-09-02 13:10:51');

-- Table structure and data for table `video_testimonials` --

-- Table structure and data for table `cms_section_items` --
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'benefits', 'ph-plant', '100% Natural', 'Nothing artificial', '', '', '10', '1', '2026-09-02 14:25:48', '2026-09-02 14:25:48');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'benefits', 'ph-orange-slice', 'Rich in Nutrients', 'Vitamins A, D, E & K', '', '', '20', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'benefits', 'ph-hexagon', 'Easy to Digest', 'A2 protein advantage', '', '', '30', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('4', 'benefits', 'ph-grains', 'Natural Fat Source', 'Goodness of ghee', '', '', '40', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('5', 'benefits', 'ph-cube', 'Daily Support', 'For a healthy lifestyle', '', '', '50', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('6', 'process', 'ph-cow', 'Free-Grazed', 'Gir Cows', '', '', '10', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('7', 'process', 'ph-drop', 'Fresh & Pure', 'A2 Milk Collection', '', '', '20', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('8', 'process', 'ph-bowl-food', 'Bilona Churning', 'in Small Batches', '', '', '30', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('9', 'process', 'ph-fire', 'Slow-Cooked', 'on Wood Fire', '', '', '40', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('10', 'process', 'ph-hands-praying', 'Handcrafted', 'with Care', '', '', '50', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('11', 'process', 'ph-jar', 'Pure Goodness', 'Every Jar', '', '', '60', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('12', 'assurance', 'ph-seal-check', '100% Natural', 'No additives', '', '', '10', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('13', 'assurance', 'ph-flask', 'Lab Tested', 'For purity & safety', '', '', '20', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('14', 'assurance', 'ph-fire', 'Bilona & Handcrafted', 'Slow process', '', '', '30', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('15', 'assurance', 'ph-heart', 'Full of Goodness', 'No shortcuts', '', '', '40', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('16', 'assurance', 'ph-plant', 'Sustainable', 'Good for our planet', '', '', '50', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('17', 'why', 'ph-cow', 'Free-Grazed Gir Cows', '', '', '', '10', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('18', 'why', 'ph-shield-check', 'No Preservatives', '', '', '', '20', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('19', 'why', 'ph-stomach', 'Easy A2 Digestion', '', '', '', '30', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('20', 'why', 'ph-fire', 'Bilona Churned', '', '', '', '40', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('21', 'why', 'ph-bowl-food', 'Small Batches', '', '', '', '50', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('22', 'why', 'ph-plant', 'Clean, Honest Products', '', '', '', '60', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('23', 'newsletter-perks', 'ph-seal-percent', 'Exclusive Offers', '', '', '', '10', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('24', 'newsletter-perks', 'ph-plant', 'Farm Updates', '', '', '', '20', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');
INSERT INTO `cms_section_items` (`id`, `section_key`, `icon`, `title`, `subtitle`, `image`, `link_url`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES ('25', 'newsletter-perks', 'ph-first-aid', 'Health Tips', '', '', '', '30', '1', '2026-09-02 14:25:49', '2026-09-02 14:25:49');

-- Table structure and data for table `blog_posts` --

-- Table structure and data for table `orders` --
INSERT INTO `orders` (`id`, `user_id`, `order_number`, `status`, `payment_method`, `payment_status`, `shipment_status`, `currency`, `subtotal`, `shipping`, `discount`, `total`, `coupon_code`, `checkout_token`, `customer_name`, `email`, `phone`, `address1`, `address2`, `city`, `state`, `pincode`, `notes`, `razorpay_order_id`, `razorpay_payment_id`, `razorpay_signature`, `dtdc_reference`, `dtdc_tracking_url`, `fulfillment_mode`, `courier_name`, `tracking_number`, `tracking_url`, `inventory_status`, `admin_note`, `payment_error`, `paid_at`, `fulfilled_at`, `cancelled_at`, `created_at`, `updated_at`) VALUES ('33', '1', 'GD260902D8D573', 'processing', 'cod', 'cod_pending', 'awaiting_fulfillment', 'INR', '7749', '0', '0', '7749', '', 'eddd8b4b53da2159490f0a9a9d1d007561a0', 'Bruno Harding', 'rulu@mailinator.com', '+1 (957) 573-4056', '96 Rocky Milton Freeway', 'Eos quae explicabo', 'Enim unde est numqua', 'Consectetur maxime', '643235', 'Repudiandae accusantium odit dolor deserunt', '', '', '', '', '', 'manual', '', '', '', 'deducted', '', '', NULL, NULL, NULL, '2026-09-02 15:16:03', '2026-09-02 15:16:03');

-- Table structure and data for table `order_items` --
INSERT INTO `order_items` (`id`, `order_id`, `product_id`, `product_name`, `quantity`, `unit_price`, `image`) VALUES ('33', '33', 'burra-sugar', 'Gawdee Burra Sugar 1kg', '1', '159', 'assets/images/products/burra-sugar.webp');
INSERT INTO `order_items` (`id`, `order_id`, `product_id`, `product_name`, `quantity`, `unit_price`, `image`) VALUES ('34', '33', 'mixme-choco', 'Gawdee MixMe — Choco 500g', '10', '759', 'assets/images/products/mixme-choco.webp');

-- Table structure and data for table `integration_logs` --
INSERT INTO `integration_logs` (`id`, `integration`, `action`, `status`, `reference`, `message`, `created_at`) VALUES ('1', 'checkout', 'create_order', 'failed', '', 'That offer code is not valid.', '2026-09-02 15:15:59');
INSERT INTO `integration_logs` (`id`, `integration`, `action`, `status`, `reference`, `message`, `created_at`) VALUES ('2', 'checkout', 'order_received', 'success', 'GD260902D8D573', 'Order saved in the fulfilment queue.', '2026-09-02 15:16:03');

-- Table structure and data for table `subscribers` --

-- Table structure and data for table `product_reviews` --

-- Table structure and data for table `order_status_events` --
INSERT INTO `order_status_events` (`id`, `order_id`, `status`, `title`, `description`, `created_at`) VALUES ('97', '33', 'processing', 'Order received', 'Cash on delivery order confirmed and sent to the fulfilment queue.', '2026-09-02 15:16:03');

SET foreign_key_checks = 1;
